### ISSUE TITLE
Register as official Julia package

### ISSUE THREAD

**Issue by lungben** [pazzo83/QuantLib.jl#14]
In my oppinion this package is very useful for a larger audience (at least it was very useful for me), therefore it would be great if you can register it as an official Julia package.

**Comment by pazzo83** [comment]
Hi!  This package should be installable via the package manager now.  Please let me know if you have any issues.  I'll keep the ticket open for a few days so you can reply if you do.

Thanks!

**Comment by lungben** [comment]
Thanks Chris! Works fine for me.
