### ISSUE TITLE
Use expm1

### ISSUE THREAD

**Issue by mschauer** [pazzo83/QuantLib.jl#2]
Just because my eye fell on it, julia has ``expm1(x)`` which is numerically stable for  ``exp(x)-1`` as for example in the Ornstein-Uhlenbeck code, ``(1.0 - exp(-2.0 * process.speed * dt))``

**Comment by pazzo83** [comment]
Thanks!  I wasn't aware of that method in Base, but I will go through and see where I can use it to replace existing code.

**Comment by pazzo83** [comment]
I think I've resolved all the instances where expm1 can be used, if any more are found, please reopen! 

https://github.com/pazzo83/QuantLib.jl/commit/89a1413f1e7212eabfc77fd88d182e7eacb5dcbc
