### ISSUE TITLE
error on runtest

### ISSUE THREAD

**Issue by nistick** [pazzo83/QuantLib.jl#7]
Error is occur in test case bonds.jl, In Windows

Error message is that
------------------------------------------------------
Test Failed
  Expression: clean_price(callableBond) == 96.46794584230872
   Evaluated: 96.46794584230878 == 96.46794584230872

in c++ version of Quantlib 
clean price of callableBond is 96.46794584230875

check Plz

**Comment by pazzo83** [comment]
Tests should now all be passing (with 1.0 updates).
